// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_appsync_graphqlEndpoint: 'https://jn4h3evmprdvbbi2fcbhebp2ca.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_cognito_identity_pool_id: 'eu-west-1:7f40c304-d647-49d0-9e96-fb045100b6ec',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_2tfEeYYKx',
  aws_user_pools_web_client_id: '71vc1e1s0v3ls2o2dqdh79aef',
  aws_user_files_s3_bucket: 's3sprint21010',
  aws_user_files_s3_bucket_region: 'eu-west-1',
  aws_mobile_analytics_app_id: '71c46d4b7bbb43cdae78a40fa53ce20b',
  aws_mobile_analytics_app_region: 'eu-west-1'
};


export default awsmobile;
