// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id: 'eu-central-1:449efb64-bfc7-4000-87c5-be32dcdc346b',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_J86767ySw',
  aws_user_pools_web_client_id: '4l8vk0al9s1bk0ac26ult7shr2',
  aws_appsync_graphqlEndpoint: 'https://nk7vsimanrhk5anjsoyvfnf7ra.appsync-api.eu-central-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-central-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'kfc1010mvpstoragebucket-dev',
  aws_user_files_s3_bucket_region: 'eu-central-1'
};


export default awsmobile;
